spring:
  application:
    name: Chatting

  datasource:
    url: jdbc:mysql://3.34.43.48:3306/chatting
    username: developer
    password: developer!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://developer:developer!!@3.34.43.48:27017/chatStorage?authSource=admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
