spring:
  application:
    name: Chatting

  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: user
    password: pass1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatStorage

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
